### ISSUE TITLE
Add link option to logo image

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-navigationLogo#26]
### Subject of the enhancement
Currently, the nav logo is just a static image. It might be useful to have the ability to make this image a link. A typical use case would be to have the logo link to the main menu (a.k.a. the "home page"), which is similar to how most web sites function.

Does anyone think this would be a useful addition?

**Comment by oliverfoster** [comment]
Yes please

**Comment by guywillis** [comment]
Preliminarily, yes. 

Though what would our approach be for assisted tech users?

**Comment by oliverfoster** [comment]
Image used alone as a linked logo
https://www.w3.org/WAI/tutorials/images/functional/
