### ISSUE TITLE
move u-display-none to "navigation-logo"

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-navigationLogo#6]
adapt-navigationLogo v2.1.0

Currently when `"_hideLogoForMobile": true`, `u-display-none` is applied to `img.navigation-logo__image`. This leaves in place the parent divs and their styling. Such remnants interfere with the goal of removing the logo and recapturing space in the navbar.

I suggest that `u-display-none` be added to `navigation-logo` instead of `img.navigation-logo__image`.
\------------------

In this first screenshot, I added a white border to `navigation-logo` to highlight what remains behind. These remnant divs push out of alignment the text "View Progress".
![nav-logo-1](https://user-images.githubusercontent.com/9489014/164953227-87027634-a0a9-49f8-99e0-9e0eb1c36223.JPG)

In this second screenshot, the white border remains in code but is not visible because I moved `u-display-none` to the parent  `navigation-logo`. Consequently, "View Progress" falls in-line.
![image](https://user-images.githubusercontent.com/9489014/164953317-b0519786-fefc-40af-a66c-9ec1f886b7bf.png)

**Comment by swashbuck** [comment]
👍  This makes sense to me.
